export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_RECEIVED = 'AUTH_RECEIVED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOAD_PERMISSIONS_REQUEST = 'LOAD_PERMISSIONS_REQUEST';
export const LOAD_PERMISSIONS_SUCCESS = 'LOAD_PERMISSIONS_SUCCESS';
export const LOAD_PERMISSIONS_FAILURE = 'LOAD_PERMISSIONS_FAILURE';
